[package]
name = "wasmdemo"
version = "1.0.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
lambda_http = "0.1.1"
lambda_runtime = "0.2.1"
serde_json = "1.0"
dotenv = "0.15.0"
